wandb_version: 1

processed:
  desc: null
  value: true
name_policy:
  desc: null
  value: Sarsa
height:
  desc: null
  value: 15
width:
  desc: null
  value: 20
gap:
  desc: null
  value: 4
True_flappy:
  desc: null
  value: false
eps:
  desc: null
  value: 0.01
alpha:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712858545.770382
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      - 12
      13: windows-amd64
